cargo-features = ["panic-immediate-abort"]

[package]
edition      = "2024"
name         = "fabseesp"
rust-version = "1.93"
version      = "0.1.0"

[dependencies]
esp-hal = { git = "https://github.com/esp-rs/esp-hal.git", features = ["defmt", "unstable"] }
esp-rtos = { git = "https://github.com/esp-rs/esp-hal.git", features = [
  "defmt",
  "embassy",
  "esp-radio"
] }
defmt = "1.0.1"
esp-bootloader-esp-idf = { git = "https://github.com/esp-rs/esp-hal.git", features = ["defmt"] }
embassy-executor = { version = "0.9.1", features = ["defmt"] }
embassy-time = { version = "0.5.0", features = ["defmt"] }
esp-backtrace = { git = "https://github.com/esp-rs/esp-hal.git", features = [
  "defmt",
  "panic-handler",
] }
esp-println = { git = "https://github.com/esp-rs/esp-hal.git", features = ["defmt-espflash"] }
embassy-net = { version = "0.8.0", features = [
    "dhcpv4",
    "medium-ethernet",
    "tcp",
    "udp",
    "defmt",
    "dns",
] }
esp-alloc = { git = "https://github.com/esp-rs/esp-hal.git", features = ["defmt"] }
esp-radio = { git = "https://github.com/esp-rs/esp-hal.git", features = [
    "defmt",
    "wifi",
    "esp-alloc",
    "unstable",
] }
static_cell = { version = "2.1.1", features = ["nightly"] }
picoserve = { version = "0.18.0", features = ["embassy", "defmt", "json"] }
ssd1306 = { version = "0.10.0", features = ["async"] }
embedded-graphics = { version = "0.8.2", features = ["defmt"] }
tinybmp = "0.7.0"
embassy-sync = "0.7.2"
nb = "1.1.0"
reqwless = { version = "0.14.0", default-features = false, features = [
    "defmt",
] }
serde = { version = "1.0.228", default-features = false, features = ["derive"] }
smoltcp = { version = "0.12.0", default-features = false, features = [
    "defmt",
    "medium-ethernet",
    "multicast",
    "proto-dhcpv4",
    "proto-dns",
    "proto-ipv4",
    "socket-dns",
    "socket-icmp",
    "socket-raw",
    "socket-tcp",
    "socket-udp",
    "dns-max-server-count-4", 
] }
heapless = { version = "0.9.2", features = ["defmt"] }
embassy-futures = { version = "0.1.2", features = ["defmt"] }
trouble-host = { version = "0.6.0", features = ["gatt", "defmt", "derive"], optional = true }
bt-hci = { version = "0.8.0", features = ["defmt"], optional = true }

[profile.dev]
opt-level = "s"
debug = "line-tables-only"
panic = "immediate-abort"

[profile.release]
codegen-units = 1
debug = true
lto = true
opt-level = 's'
panic = "immediate-abort"

[features]
esp32c6 = [
    "esp-backtrace/esp32c6",
    "esp-bootloader-esp-idf/esp32c6",
    "esp-rtos/esp32c6",
    "esp-hal/esp32c6",
    "esp-radio/esp32c6",
    "esp-radio/ble",
    "esp-println/esp32c6",
    "trouble-host",
    "bt-hci",
]

esp32 = [
    "esp-backtrace/esp32",
    "esp-bootloader-esp-idf/esp32",
    "esp-rtos/esp32",
    "esp-hal/esp32",
    "esp-radio/esp32",
    "esp-radio/ble",
    "esp-println/esp32",
    "trouble-host",
    "bt-hci",
]

esp32s2 = [
    "esp-backtrace/esp32s2",
    "esp-bootloader-esp-idf/esp32s2",
    "esp-rtos/esp32s2",
    "esp-hal/esp32s2",
    "esp-radio/esp32s2",
    "esp-println/esp32s2",
]
